Install provider via Crossplane as a package in local dev environment
vshn/provider-cloudscale pull request #26
Opened 2022-07-28 13:53 UTC by ccremer

## Summary

* This PR turns the local environment into 

## Checklist

### For Code changes

- [ ] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [ ] PR contains the label `area:operator`
- [ ] Link this PR to related issues
- [ ] I have not made _any_ changes in the `charts/` directory.

### For Helm Chart changes

- [ ] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [ ] PR contains the label `area:chart`
- [ ] PR contains the chart label, e.g. `chart:provider-cloudscale`
- [ ] Variables are documented in the values.yaml using the format required by [Helm-Docs](https://github.com/norwoodj/helm-docs#valuesyaml-metadata).
- [ ] Chart Version bumped if immediate release after merging is planned
- [ ] I have run `make chart-docs`
- [ ] Link this PR to related code release or other issues.

2022-07-28 15:01 UTC, ccremer commented
For testing this PR: 
Follow the quickstart section in the readme and inspect the results

2022-07-29 07:01 UTC, Kidswiss requested changes
Building the package fails for me with a linting error:
```
gmake package-provider
kubectl crossplane: error: failed to build package: failed to lint package: not exactly one package meta type
gmake: *** [package/package.mk:20: package-provider] Error 1
```

EDIT: renaming `crossplane.yaml.template` to `crossplane.yaml` fixes the issue. I guess something is supposed to transform the template file?

2022-07-29 07:35 UTC, ZuGao commented
Having the same issue as @Kidswiss:
`kubectl crossplane: error: failed to build package: failed to lint package: not exactly one package meta type`

2022-07-29 07:42 UTC, ccremer commented on operator/bucketcontroller/setup.go
> -// +kubebuilder:rbac:groups=cloudscale.crossplane.io,resources=buckets,verbs=get;list;watch;create;update;patch;delete
It's magic by Crossplane installation. First I was under the impression I had to add the rules to access the CRDs and put them under `permissionRequests`, turns out this caused more harm than help. My guess is that Crossplane analyzes the CRDs and gives basically enough permissions to the SA.
Now that I have removed these markers and also removed the yq command that imported the kubebuilder-generated RBAC rules before to the permissionRequests you noticed the issue with `crossplane.yaml.template`. Oversight from my side, I'll fix it.

2022-07-29 07:53 UTC, ccremer commented
I've fixed the package generation. you're invited to test again

2022-07-29 10:56 UTC, Kidswiss approved these changes
Seems to be working now.

2022-07-29 11:33 UTC, merged